TICKETS: tuple[str, ...] = (
    "USD",
    "BTC",
    "ETH",
    "DOT",
    "WRX",
    "BNB",
    "MATIC",
    "MDX",
    "ATOM",
    "LUNC",
    "RUNE",
    "ADA",
    "XRP",
    "SAND",
    "SOL",
    "AVAX",
)
TYPES = {
    "USD": "currency",
    "BTC": "cryptocurrency",
    "ETH": "cryptocurrency",
    "DOT": "cryptocurrency",
    "WRX": "cryptocurrency",
    "BNB": "cryptocurrency",
    "MATIC": "cryptocurrency",
    "MDX": "cryptocurrency",
    "ATOM": "cryptocurrency",
    "LUNC": "cryptocurrency",
    "RUNE": "cryptocurrency",
    "ADA": "cryptocurrency",
    "XRP": "cryptocurrency",
    "SAND": "cryptocurrency",
    "SOL": "cryptocurrency",
    "AVAX": "cryptocurrency",
}
NAMES = {
    "USD": "US Dollar",
    "BTC": "Bitcoin",
    "ETH": "Ethereum",
    "DOT": "Polkadot",
    "WRX": "Wazirx",
    "BNB": "Bnb",
    "MATIC": "Polygon",
    "MDX": "Mdex (HECO)",
    "ATOM": "",
    "LUNC": "",
    "RUNE": "",
    "ADA": "",
    "XRP": "",
    "SAND": "",
    "SOL": "",
    "AVAX": "",
}
COINGECKO_IDS = {
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "DOT": "polkadot",
    "WRX": "wazirx",
    "BNB": "binancecoin",
    "MATIC": "matic-network",
    "MDX": "mdex",
    "ATOM": "cosmos",
    "LUNC": "terra-luna",
    "RUNE": "thorchain",
    "ADA": "cardano",
    "XRP": "ripple",
    "SAND": "the-sandbox",
    "SOL": "solana",
    "AVAX": "avalanche-2",
}
